### ISSUE TITLE
invalid value for "locale"

### ISSUE THREAD

**Issue by nglelinh** [highsidelabs/amazon-business-api#2]
I am trying to use the search product API, but getting the following error

```
InvalidArgumentException  : invalid value for "locale" when calling ProductSearchV20200826Api.productsRequest, must conform to the pattern /^[-_]+$/.
```

The locale value in example _en_US_ can not pass validation in https://github.com/highsidelabs/amazon-business-api/blob/01469e5c5a4057119b2bd97add46025d60fdc1b6/lib/Api/ProductSearchV20200826Api.php#L906

Please help to explain why do we have such validation ? and which value should I submit to go through this checking ?

**Comment by jlevers** [comment]
Sorry, this took me quite a while to get around to.

Those regexes were there because they're included in the Amazon OpenAPI models for this API, but I agree that they're incorrect. They've been removed in `v1.0.3`.
