### ISSUE TITLE
Delivery Information error

### ISSUE THREAD

**Issue by brightherodev** [highsidelabs/amazon-business-api#3]
Thanks for your package. Your package is very useful for Amazon Business api.
I found one issue in delivery information type.

In https://github.com/highsidelabs/amazon-business-api/blob/main/lib/Model/ReportingV20210108/DeliveryInformation.php

    const DELIVERY_STATUS_DELIVERED = 'DELIVERED';
    const DELIVERY_STATUS_NOT_DELIVERED = 'NOT DELIVERED';
    const DELIVERY_STATUS_NOT_AVAILABLE = 'NOT AVAILABLE';
    
 Btw, real response delivery status is
 DELIVERY_STATUS_NOT_DELIVERED = 'NOT_DELIVERED'
 DELIVERY_STATUS_NOT_AVAILABLE = 'NOT_AVAILABLE'
   
How can fix this?

**Comment by jlevers** [comment]
Sorry for the slow response -- I had forgotten to turn on issue notifications for this repo. Your issue should be fixed in `v1.1.0`.
